services:
  - type: web
    name: renarx-api
    env: node
    buildCommand: npm install --omit=dev
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_hW6Qox8usLeE@ep-autumn-haze-apc6ffel-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        value: 10000000
      - key: SMS_ENABLED
        value: false
      - key: PAYMENT_ENABLED
        value: false
      - key: OTP_STRICT
        value: false
      - key: CLIENT_URL
        value: https://renarx.vercel.app
      - key: MINI_APP_URL
        value: https://renarx.vercel.app/
      - key: OPERATOR_PHONES
        value: "331350206"
      - key: OPERATOR_NAME
        value: "Ismoiljonov Mustafo"
      - key: OPERATOR_TELEGRAM
        value: "@ReNarx_admin"
